### ISSUE TITLE
Porkbun DDNS fails with 404 error via caddy

### ISSUE THREAD

**Issue by LorenDB** [libdns/porkbun#5]
I [reported an error with Porkbun DDNS](https://caddy.community/t/problems-with-porkbun-ddns/21930) on the Caddy forums and was recommended to open an issue here.

The problem seems to be that something, apparently in this module, is requesting an API endpoint that doesn't exist; Porkbun is responding with a 404 page. Do you think that this is a problem in this module?

**Comment by cajomar** [comment]
I'm also experiencing this error.
After playing around with the porkbun API endpoints used by this module, it seems the error `The URI you submitted has disallowed characters.` is triggered by sending `@` as the `name` for root domains.
According to the [porkbun api docs](https://porkbun.com/api/json/v3/documentation), the field should instead be omitted:
> * __name__ - optional
>  The subdomain for the record being created, not including the domain itself. Leave blank to create a record on the root domain. Use * to create a wildcard record.

So instead of hitting `/dns/retrieveByNameType/example.com/A/@` we should hit `/dns/retrieveByNameType/example.com/A`.
The request to `/dns/edit/example.com/12345678` should remove the `name` field from the body sent.

**Comment by rossmarkflo** [comment]
Having the same issue - was there ever a solution to this?

**Comment by LorenDB** [comment]
I don't know that this was ever fixed. I'm using dness for now to manage my DDNS.

**Comment by Daemoen** [comment]
It definitely has not been fixed, and it's the use of '@' in general.  You *cannot* define a 'root' entry with the module.
